### ISSUE TITLE
Improve base code for box2d implementation

### ISSUE THREAD

**Issue by grant-strayvoltage** [grant-strayvoltage/gameoff#1]
Improve how the model for how children of GameMapObject setups up it's body and fixture. Right now it uses global variables as parameters and requires mostly overriding and rewriting all of addToWorld if tweaks are required.

Also refactor categories and document clearly how filter category bits are used. For example players, power cube, static and moving physics objects like platforms and blocks vs the static map tiles.

Lastly refactor how tile map is converted to box2d - right now it puts all tiles present as solid, even though some are 'death' tiles.

**Comment by kyperbelt** [comment]
hey i know you already claimed this so i hope im not stepping on toes but i couldnt really pick any of the other issues out because this one is kind of important. I made some slight additions feel free to decline/change them

**Comment by kyperbelt** [comment]
implemented simple collision detection. Very simple to use and should be easy to understand and help us moving forwards to create things such as hazards one way platforms and switches :)
